# Generated by Django 2.1.2 on 2018-10-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubber',
            fields=[
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('student_number',),
            },
        ),
    ]
