# Generated by Django 2.1.2 on 2018-12-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubber',
            fields=[
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('clubber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Clubber')),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ('clubber',),
            },
        ),
    ]
