# Generated by Django 2.1.2 on 2019-02-06 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('eventclubber', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('clubber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clubber')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'clubber')},
        ),
    ]
