# Generated by Django 2.1.2 on 2018-10-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clubber')),
            ],
            options={
                'ordering': ('student_number',),
            },
        ),
    ]
