# Generated by Django 2.1.2 on 2019-02-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('clubber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Clubber')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendancenew',
            unique_together={('event', 'clubber')},
        ),
    ]
