# Generated by Django 2.1.2 on 2018-12-21 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clubber_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubber',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='degree_program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='email_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='emergency_contact',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='emergency_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='emergency_relationship',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='mobile_number',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='nick_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='permanent_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Executive Secretary', 'Executive Secretary'), ('Associate Secretary', 'Associate Secretary'), ('Director', 'Director'), ('Project Manager', 'Project Manager'), ('Member', 'Member')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='present_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubber',
            name='project',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubber',
            name='committee',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Academics', 'Academics'), ('Externals', 'External Affairs'), ('Extracurricular', 'Extracurricular Affairs'), ('Finance', 'Finance'), ('Internals', 'Internal Affairs'), ('Membership', 'Membership'), ('Publicity', 'Publicity')], default='', max_length=100),
        ),
    ]
