# Generated by Django 2.1.2 on 2018-12-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181221_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubber',
            name='committee',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Academics', 'Academics'), ('Externals', 'Externals'), ('Extracurricular', 'Extracurricular'), ('Finance', 'Finance'), ('Internals', 'Internals'), ('Membership', 'Membership'), ('Publicity', 'Publicity')], default='', max_length=100),
        ),
    ]
