# Generated by Django 2.1.2 on 2018-12-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
