# Generated by Django 2.1.2 on 2019-01-03 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_announcement_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaff',
            fields=[
                ('sem', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ('sem',),
            },
        ),
        migrations.CreateModel(
            name='ReaffedClubber',
            fields=[
                ('clubber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Clubber')),
                ('submitted_docs', models.BooleanField()),
                ('updated_db', models.BooleanField()),
                ('paid_fee', models.BooleanField()),
                ('reaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Reaff')),
            ],
        ),
    ]
