# Generated by Django 2.1.2 on 2019-01-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_reaff_reaffedclubber'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaffedclubber',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
