# Generated by Django 2.1.2 on 2019-01-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reaffedclubber_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProcess',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reaffedclubber',
            name='clubber',
        ),
        migrations.RemoveField(
            model_name='reaffedclubber',
            name='reaff',
        ),
        migrations.DeleteModel(
            name='Reaff',
        ),
        migrations.DeleteModel(
            name='ReaffedClubber',
        ),
    ]
