# Generated by Django 2.1.2 on 2019-01-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190109_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaffedClubber',
            fields=[
                ('clubber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.Clubber')),
                ('last_name', models.CharField(max_length=100)),
                ('updated_db', models.BooleanField()),
                ('submitted_docs', models.BooleanField()),
                ('paid_fee', models.BooleanField()),
            ],
        ),
    ]
