# Generated by Django 2.1.2 on 2019-01-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_reaffedclubber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('student_number', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('committee', models.CharField(choices=[('Executive', 'Executive'), ('Academics', 'Academics'), ('Externals', 'Externals'), ('Extracurricular', 'Extracurricular'), ('Finance', 'Finance'), ('Internals', 'Internals'), ('Membership', 'Membership'), ('Publicity', 'Publicity')], default='', max_length=100)),
                ('position', models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Executive Secretary', 'Executive Secretary'), ('Associate Secretary', 'Associate Secretary'), ('Director', 'Director'), ('Project Manager', 'Project Manager'), ('Member', 'Member')], default='', max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('degree_program', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_relationship', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clubber',
            name='av_equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='carpool_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clubber',
            name='instruments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='sports_equipment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
