# Generated by Django 2.1.2 on 2019-01-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190115_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending',
            name='av_equipment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='carpool_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pending',
            name='instruments',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='sports_equipment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
