# Generated by Django 2.1.2 on 2019-01-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190115_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubber',
            name='committee',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Academics', 'Academics'), ('Externals', 'Externals'), ('Extracurricular', 'Extracurricular'), ('Finance', 'Finance'), ('Internals', 'Internals'), ('Membership', 'Membership'), ('Publicity', 'Publicity'), ('TBA', 'TBA')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubber',
            name='position',
            field=models.CharField(choices=[('President', 'President'), ('Vice President', 'Vice President'), ('Executive Secretary', 'Executive Secretary'), ('Associate Secretary', 'Associate Secretary'), ('Director', 'Director'), ('Project Manager', 'Project Manager'), ('Member', 'Member'), ('TBA', 'TBA')], default='', max_length=100),
        ),
    ]
