# Generated by Django 2.1.2 on 2019-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190115_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaffedclubber',
            name='ew_jersey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaffedclubber',
            name='ew_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reaffedclubber',
            name='read_contract',
            field=models.BooleanField(default=False),
        ),
    ]
