# Generated by Django 2.1.2 on 2019-01-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190116_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubber',
            name='candy',
            field=models.CharField(choices=[('Chocnut', 'Chocnut'), ('Choco Choco', 'Choco Choco'), ('Flat Tops', 'Flat Tops'), ('Potchi', 'Potchi')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='closest_friends',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='current_subjects',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='ieaid_company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='ieaid_contactdetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='clubber',
            name='ieaid_contactperson',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='candy',
            field=models.CharField(choices=[('Chocnut', 'Chocnut'), ('Choco Choco', 'Choco Choco'), ('Flat Tops', 'Flat Tops'), ('Potchi', 'Potchi')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='closest_friends',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='current_subjects',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='ieaid_company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='ieaid_contactdetails',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pending',
            name='ieaid_contactperson',
            field=models.CharField(default='', max_length=100),
        ),
    ]
