# Generated by Django 2.1.2 on 2019-01-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190116_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubber',
            name='closest_friends',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pending',
            name='closest_friends',
            field=models.CharField(default='', max_length=255),
        ),
    ]
