# Generated by Django 2.1.2 on 2019-01-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190118_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubber',
            name='current_subjects',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pending',
            name='current_subjects',
            field=models.CharField(default='', max_length=255),
        ),
    ]
