# Generated by Django 2.1.2 on 2019-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('student_number', models.CharField(max_length=250)),
            ],
        ),
    ]
