# Generated by Django 2.1.2 on 2019-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0002_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
