# Generated by Django 2.1.2 on 2019-06-02 11:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer', '0004_auto_20190602_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
