# Generated by Django 2.1.2 on 2019-04-10 03:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_description', models.CharField(max_length=100)),
                ('units', models.IntegerField(default=0)),
                ('isJS', models.BooleanField()),
                ('isSS', models.BooleanField()),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
                ('corequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('curriculum_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculumchecker.Curriculum'),
        ),
    ]
